---
title: "Resources to help you begin your coding journey"
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# RStudio Cloud
In the workshops, we will use RStudio Cloud, which is a "lightweight, cloud-based solution that allows anyone to do, share, teach and learn data science online". This will allow us to share all of our code online and will make it easier for us to help answer all of your coding questions. For more information, you can check out the website [here](https://rstudio.cloud/).

This platform is completely free for you to use, but you will need to set up an account. To do so, please follow the instructions below:

1. 
2. 
3. 

# R & RStudio
RStudio Cloud is great for beginners and getting started with R, but you will eventually want to work on your own computers. So, after the first couple of workshops, we will show you how to transfer all of your files to your local computers (as opposed to working on the cloud). To do this, you will need to have both R and RStudio installed. 

***Please have these installed/downloaded before Workshop #3***

- You can install **R** from the [CRAN (Comprehensive R Archive Network) website](https://cran.r-project.org/). I suggest downloading the latest version, which (as of the time of writing this workshop) is R 4.1.1
  - [R for Windows link](https://cran.r-project.org/bin/windows/base/)
  - [R for Mac link](https://cran.r-project.org/)
- You can download **RStudio** [here](https://www.rstudio.com/products/rstudio/download/)
- Although you need to have R installed, you will mostly likely never need to open R because you can do everything you need in RStudio

# Additional R Resources

- [R-Ladies Sydney RYouWithMe Tutorials](https://rladiessydney.org/courses/ryouwithme/). There are 4 different units within these tutorials:
  - **BasicBasics** includes a tour of RStudio, how to install and load packages, and how to get data into RStudio
  - **CleanItUp** introduces a few very popular packages (including `tidyverse` which we will learn all about!) and how to use a few functions to "wrangle" (or clean and organize) your data 
  - **VizWhiz**: introduces `ggplot` and gives examples of how to plot data to create beautiful visualisations in R
  - **MarkyMark**: introduces R Markdown (which we will also learn all about!)

- Feel free to check out a blog post written by Jenny on [Introduction to R](https://jennysloane.netlify.app/blog/intro_to_r/). Some of the topics covered include: getting familiar with RStudio, working directories, R Markdown, and tidyverse!